DROP SCHEMA IF EXISTS elr;
CREATE SCHEMA elr;
USE elr;

DROP TABLE IF EXISTS 'Admin';
CREATE TABLE 'Admin'(
    ID INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(32) DAEFAULT NULL,
    PASSWORD VARCHAR(32) DAEFAULT NULL,
    EMAIL VARCHAR(32) DAEFAULT NULL,);
    
DROP TABLE IF EXISTS 'RESIDENTS';
CREATE TABLE 'Admin'(
    ID INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,)